### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by ammannit** [sttz/install-unity#26]
Hi

Nice tool and it is really helpful. But we get this error message when we want to install the unity with package:

"the value must be greater than or equal to zero and less than the console's buffer size in that dimension. Parameter name: top
Actual value was -16."

Have you a idea?

Thanks for your help :)

Best Regards :)

**Comment by sttz** [comment]
Hey, thanks for the report!

Can you try running install-unity with `-v` and reproducing the error? This should print the stack trace of the error and make it more clear where the error is occurring.

Do you use another terminal app than the default one? What are the arguments passed to install-unity?

You can try disabling the progress bar by adding the `--opt=progressBar=false` argument, to see if the error is in the progress bar rendering.

**Comment by sttz** [comment]
I've fixed a few issues with the progress bar rendering in 2.8.1. Errors during the progress bar rendering now also only disable the progress bar and don't stop the whole installation.

Let me know if you still have issues, also if you run into a case where the progress bar gets disabled due to an error.

**Comment by Decavoid** [comment]
Here is the error:
```
at@Andreis-Mac-mini ~ % echo 9108 | sudo -S install-unity -v install 2021.3.18f1 --packages Unity,WebGL --opt installPathMac=/Applications/UnityEditor/18f1
install-unity v2.11.1
Log level set to Information
Use default configuration
Loaded versions cache from '/Users/at/Library/Application Support/install-unity/cache.json'
Install steps: DownloadAndInstall

Selected packages:
- Unity (2.76 GB)
- WebGL (584.81 MB)

Will download 3.33 GB and install 7.73 GB
Downloading packages to '/tmp/install-unity/Unity 2021.3.18f1 (3129e69bc0c7)'
                                                                                                                                                                                                                      HASH Unity                  ║▏····························································································································································║                                                                                                                                                                                        0 B of   2.76 GB @       0 B/sHASH WebGL                  ║▏····························································································································································║                                                                                                                                                                                        0 B of 584.81 MB @       0 B/s                                                                                                                                                                                                                      WARN:  Progress bar disabled due to exception during rendering: System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -4.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at sttz.InstallUnity.InstallUnityCLI.WriteQueueStatus(Queue queue, Int64 updateCount, Int32 statusInterval) in /private/tmp/install-unity-20230427-7340-va4atn/install-unity-2.11.1/Command/Program.cs:line 1216
   at sttz.InstallUnity.InstallUnityCLI.Install() in /private/tmp/install-unity-20230427-7340-va4atn/install-unity-2.11.1/Command/Program.cs:line 1090


```
